### ISSUE TITLE
Dockerfiles

### ISSUE THREAD

**Issue by ehuggett** [phpList/phplist-docker#1]
Can the Dockerfiles used to create the images hosted at https://hub.docker.com/u/phplist/ be included in this repository?

**Comment by samtuke** [comment]
That's a good question for @michield

**Comment by michield** [comment]
Those are on the internal branch in the gitlab mirror of the repo. I may publish them here later, but I've added you to the project. https://gitlab.com/phpList/phplist-docker/tree/internal

**Comment by ehuggett** [comment]
Docker is making me a little nervous about copyright/license compliance.

There is no issue with the Dockerfiles themselves, they are akin to scripts referencing copyrighted resources, but publishing images (ie the Docker hub) seems like it could entail a lot of responsibilities?

**Comment by ehuggett** [comment]
Thanks, I now have a phplist container based on your Dockerfile but using https://hub.docker.com/_/php/ as the base image (mainly just experimenting, but I might suggest some changes if I do anything useful).

**Comment by michield** [comment]
Yes, of course, that would be great. Maybe branch or fork away first and then PR the changes.

**Comment by jryberg** [comment]
Hi,

I would like to have access to the Dockerfile as well and also permission to fork it.

Depending how much work there is to get it up and running I might be able to contribute

**Comment by michield** [comment]
I'll try to spend some time to review them and make them ready for public viewing. As I recall, they're a bit messy at the moment :-)

**Comment by michield2** [comment]
Reviewing it was taking too long, so I've now pushed the branch "develop". It's unstable, but worked for me. Feel free to send PRs and the like :-)

**Comment by michield** [comment]
Logged in as a shadow account on the last comment. @jryberg Have you managed to get the code? Any issues with it?

**Comment by jodumont** [comment]
@michield releasing the Dockerfile will 
1' enthusiasm people and let them try to tweak it ;)
2' probably release pressure from your side 

such I was expecting, a Dockerfile to probably fork it then make it available under alpine

**Comment by michield** [comment]
The unstable code is [here](https://github.com/phpList/phplist-docker/tree/develop)

**Comment by michield** [comment]
Yes, my intention is to create a production version. However, lack of time, and a faulty laptop has delayed that a little.

**Comment by samtuke** [comment]
@michield How about listing the outstanding tasks in a github issue so that @derbobby and others can help iron out the kinks? E.g. like https://github.com/phpList/core/issues/238

**Comment by michield** [comment]
the develop branch has now been merged into master. If you use a versioned container, it will send the mails for real. Only the latest/dev one will not send out any emails.
