### ISSUE TITLE
What number version is the current phplist version?

### ISSUE THREAD

**Issue by ethancedwards8** [phpList/phplist-docker#10]
Title

**Comment by ethancedwards8** [comment]
How do we make the container actually send emails out? Currently it says that it's work in progress. How far is it from production ready/what else does it need? Is there any way I could help?

**Comment by michield** [comment]
The versioned ones will send out for real. I will try to get those back to the latest version soon. If you want, you can build it yourself from the zip file. It's probably not a good idea to have the latest one in production.

**Comment by michield** [comment]
3.5.5 is now available on docker hub

**Comment by ethancedwards8** [comment]
Awesome, thanks. Would you accept a donation/tip?

**Comment by michield** [comment]
You're welcome. Not to worry :-) A donation to your favourite charity would be sufficient.
