### ISSUE TITLE
Unable to start a dev environment : error copying from phplist-unknown/

### ISSUE THREAD

**Issue by hedrickbt** [phpList/phplist-docker#14]
I have tried setting the version via the .env file and export without any change.

my .env file
~~~~~~~~~~~~~~~~~~~~~~~~~~
PORT=8000
HOSTNAME=localhost
THEME_DEV_PATH=/home/testuser/phplist/themes
CODE_PATH=/home/testuser/phplist/phplist3/public_html/
PLUGIN_DEV_PATH=/home/testuser/phplist/plugins
~~~~~~~~~~~~~~~~~~~~~~~~~~

./start-phplist.sh
..
=> CACHED [11/15] RUN echo VERSION=unknown                                                                                                                                   0.0s
 => CACHED [12/15] RUN rm -rf /var/www/phpList3 && mkdir /var/www/phpList3                                                                                                    0.0s
 => ERROR [13/15] COPY phplist-unknown/ /var/www/phpList3

**Comment by michield** [comment]
It's trying to build the image, by the looks of it. That's not necessary

What happens if you run

`docker-compose -f phplist-dev.yml up -d`

**Comment by hedrickbt** [comment]
Same result.

~~~
 => CACHED [11/15] RUN echo VERSION=unknown                                                                                                                                                               0.0s
 => CACHED [12/15] RUN rm -rf /var/www/phpList3 && mkdir /var/www/phpList3                                                                                                                                0.0s
 => ERROR [13/15] COPY phplist-unknown/ /var/www/phpList3                                                                                                                                                 0.0s
------
 > [13/15] COPY phplist-unknown/ /var/www/phpList3:
------
failed to compute cache key: "/phplist-unknown" not found: not found
ERROR: Service 'phplist' failed to build
~~~

To be able to work, I...
1. Modified phplist/Dockerfile
...
#COPY phplist-${VERSION}/ /var/www/phpList3
#COPY docker-phplist-config-live.php /var/www/phpList3/config.php

#RUN mkdir -p /var/www/phpList3/public_html/images && \
#       mkdir -p /var/www/phpList3/public_html/lists/admin/plugins && \
#    chmod 777 /var/www/phpList3/public_html/images && \
#    chmod 777 /var/www/phpList3/public_html/lists/admin/plugins
...
#VOLUME ["/var/www", "/var/log/apache2"]
...


2. Built my own image from that Dockerfile
3. Modified phplist-dev.yml to reference the image I built
-     image: phplist/phplist:latest
+     image: phplist/phplist:bth
4. Ran the ./start... command

Then, I was able to work.

**Comment by michield** [comment]
Reported working now
