### ISSUE TITLE
phplist don't send email

### ISSUE THREAD

**Issue by akoscomp** [phpList/phplist-docker#19]
From 3.6.7 docker version of phplist don't send emails.
I think that happens with cron.
Befor 3.6.7 version, the cron file was places /phplist-crontab and from this file the entrypoint created /var/spool/cron/crontabs/root file.
From 3.6.7 the cron file moved to /etc/cron.d/phplist-crontab and the cron process normally execute it, but I think that this execution don't happen.
Because this repo don't contain this modification, I can't try to fix it, with a pull request.

**Comment by akoscomp** [comment]
I found the problem source.
this is the installed crontab file:
```
*/1 * * * * phplist -pprocessqueue >> /dev/stdout
0 3 * * * phplist -pprocessbounces >> /dev/stdout
```
but the first parameter after timeing is the username, not the command.
This is the correct and working version of the file:
```
*/1 * * * * root phplist -pprocessqueue >> /dev/stdout
0 3 * * * root phplist -pprocessbounces >> /dev/stdout
```

With this modification I solved the problem.

**Comment by michield** [comment]
Thanks for finding that.
