### ISSUE TITLE
Update phplist via docker

### ISSUE THREAD

**Issue by maziyarpanahi** [phpList/phplist-docker#2]
Hi,

We have `phplist` as a docker for small academic newsletter. The process of updating/upgrading `phplist` via docker is not mentioned anywhere so I am assuming is straightforward like pulling the latest images?

Which brings us to the second issue, how often you guys update `phplist/phplist` on Docker Hub and why does it only have one tag? Having tags with the same version allows us to choose or go back. Besides, it's not possible to know what is `latest` when it was updated 2 months ago.

As this is an open source project, I am offering help regarding pushing a new version into DockerHub and also make the tags available align with the versions if help is needed :)

**Comment by samtuke** [comment]
@maziyarpanahi 

1. Cool that you're using it
2. Thanks for offering
3. Yes you can help!

If you're offering to push new Docker versions to DockerHub following tarball releases, then what do you need access to in order to do that?

**Comment by maziyarpanahi** [comment]
Hi @samtuke and thanks for your quick reply.
For the moment, I would like to know the way you update the Docker Hub just to be on the same page in terms of producing the same stable docker image.

Then, I will try it on my Docker Hub with all the versions. When it's done, you can add me to Docker Hub and allow me to push it directly on `phplist` account (or we can make some automation for that)

But for now, I would like to know how you make an image from the latest release so I can go back and reproduce it for at least everything after version 3.x

Again, thanks :)

**Comment by michield** [comment]
I have just pushed 3.3.6: https://hub.docker.com/r/phplist/phplist/tags/

You can use the following environment vars to use it:

       DB_HOST
       DB_USER
       DB_PASSWORD
       DB_NAME
       MAILHOST

The mailhost needs to operate on port 25.

**Comment by maziyarpanahi** [comment]
That is great @michield! Thank you. I am available if you need any help now or in future :)

Thanks again!

**Comment by maziyarpanahi** [comment]
@michield sure I'll do. Thanks again I appreciate it :)
